name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Build Windows binary
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Create ZIP
        run: Compress-Archive -Path target\x86_64-pc-windows-msvc\release\pomodors.exe -DestinationPath pomodors-windows.zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: pomodors-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN
